apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCcKPLLLOwQPYqo9eN2We3HeMsKpI5fKwJGuHitnmwYiMg6l+C7Zo5cjE8QwBejQOucVdDzeUDUjj6p7S10m6noknUNaoflKFLwl1y1FRHM7PVa9Fo3AjqgSCqoRVSxs2uZSaMiWWd79EPIoVQ/m9VI9KfPbFndt+yLNezzzkauz+jAL8aifqymgUZGzNnmM/cs5wDXJ8ko9ZoJzFk8R0SfuVw6Bc1pgeHQocyd05IlZuf8OYwBQom4XnUMFyyV6PkijzUSxEVapkYVnZgWnF/VF4lGAfqTZ+5qmOCzZwI9mde6xYvc4+XX5sdmkQyE612f3GRN1hpCkAVz9eTEImYxOL88r2Wiz8el+pAn0hjuI0mDqCHBLoBkmArDYcjVJJP58uOEESUuYQaHVUt4Za2xRjLkY/GK7XQFNxkJeJwF0lIpVJM/vNk3MEtkrQPKXA+uYKpyTu7vN5BcDQHuNpLbMwh31Wqeqx0PoiRqwovsXHm1kJE+gLw+CGKKhJpheExKRpM7+65Kd5MczONPnreskZXFosJwUEhNLo7R+P4Xv2c8Ln7G1T3DkKc/bvYpNAtZeM29IpFZL6b2x26PamO4LaXQh4i+nqq/8WQizkhI5CUZ0hYK4XQe6rG/Iyi08LT9pqM3aSrsBZ61aEqEBu58jiGCYTUWIzHMhtnV8K0P6kxvjZXK2ZqE0hxm0lpb65UgwIQ60SinUA==
    DB_USER: AgBkbLCSNYb9RRn13A8GeuGUbwHmAFGiRK1Njv01swlyXCujaIVpltPp2n/j8SSTsm0t+SZYaMErQeqQ8yrE5aLiIPgAM2pp9FukRM4xwqnIO+9RpH03fILYAWB0TCbWb/KNA3FVMsFtiiAmQ9/PavU94LzFQELZL8r8jlHHP86Gn9CQYciu16g9HRP2M4fjhxdaPQ3ni9XuetXvsxpCEdnq0FqZlZxuJb4gwzZGwwHNNYFC+q+W5xHMlZQuxMz4brbNIjAMaB3N76K46nqsMmpVrNHc718SFcEWUeikwYQmWbG/QprA/iZCyWXjXFb0VplT/6s25XVkRiBmk730MqBBvUAe7viR3R+r1v/I2ZwLx1pRDvnTSenycHjw4b7Zk+oyYLWxCi8nK38SjZsOhdlQWcN4kX7HSX/QXoZUNpDuppGYikGFxwW/qP+rrgxOqBc6+LXVXJ+5KqCLIhuAXBvhEoz4yqKEQM1QYi3vPGAAaF6TG1TrIf4JCS4ngRlUN2zPdOOxO4pH2jq0W6yjDA5A7MbJxW8czGTH+da4YvC6cuFfOndS5FqfMDdjBADQH2vwUi5mHNYmhpGVTrv+Z86CYLharG3fux+15zIUkgCxHmhHvP7aUq82jtVbQO/AW65PssYY/AGJJXdSQkxlEOhyJ44bJDUEOosfaS5UhjRxxURPbEc0aTSg+OBeS7HoujLfxuVulYuABg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

